@extends('layouts.web')
@section('content')
    @include('includes.web.carousel')
    {{--@include('includes.web.about')--}}
    @include('includes.web.features')
    @include('includes.web.services')
    @include('includes.web.portfolio')
    @include('includes.web.team')
    @include('includes.web.contact')
@endsection