@extends('layouts.web')
@section('content')
    @include('includes.web.hero')
    @include('includes.web.features')
    @include('includes.web.portfolio')
    {{--@include('includes.web.services')--}}
    @include('includes.web.blog')
    {{--@include('includes.web.team')--}}
    @include('includes.web.contact')
@endsection